#!/usr/bin/env bash

if [ ! -n "$VIRTUAL_ENV" ]; then
        echo "VENV is not active"

        if [ ! -f .venv/bin/activate ]; then
                echo ".venv/bin/activate file not found"
                echo "Running 'python3 -m venv .venv"
                python3 -m venv .venv
        fi

        echo "Activating VENV"
        source .venv/bin/activate
fi

echo "Installing required packages"
pip install -r requirements.txt

echo "Starting the app"
uvicorn main:app --reload
